image: docker:latest

variables:
  RESOURCE_GROUP_NAME: my-azure-rg
  APP_NAME: my-app-name
  LOCATION: eastus
  IMAGE_NAME: my-image-name
  DOCKERFILE_PATH: .
  CONTAINER_PORT: 8080
  TERRAFORM_VERSION: 1.0.9

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME $DOCKERFILE_PATH
    - echo "$REGISTRY_PASSWORD" | docker login <your-registry-name>.azurecr.io -u "$REGISTRY_USERNAME" --password-stdin
    - docker tag $IMAGE_NAME <your-registry-name>.azurecr.io/$IMAGE_NAME
    - docker push <your-registry-name>.azurecr.io/$IMAGE_NAME
  tags:
    - docker

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:$TERRAFORM_VERSION
    entrypoint: [""]
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - ssh-keyscan $APP_NAME.azurecontainer.io >> ~/.ssh/known_hosts
    - terraform init
    - terraform apply -auto-approve -var="resource_group_name=$RESOURCE_GROUP_NAME" -var="app_name=$APP_NAME" -var="location=$LOCATION" -var="image_name=$IMAGE_NAME" -var="container_port=$CONTAINER_PORT"
  environment:
    name: production
  only:
    - master
